### ISSUE TITLE
Does EdgePanTransition work for UITableView? 

### ISSUE THREAD

**Issue by adaoli** [lkzhao/ElasticTransition#8]
When try function handleLeftPan(pan:UIPanGestureRecognizer) in a UIView it works perfectly. But when try it on a UITableView, i got error "fatal error: unexpectedly found nil while unwrapping an Optional value"   for code line transition.dissmissInteractiveTransition. 

Already tried changing UIViewController to UITableViewController as below for function dissmissInteractiveTransition, but it's not working. 
public func dissmissInteractiveTransition(viewController:UITableViewController, gestureRecognizer 

Thank you and apologize in case it's a silly question.

**Comment by lkzhao** [comment]
Can you provide an example project. I can help you debug. The transition should work with uitableviewcontroller though, since it is a subclass of uiviewcontroller

**Comment by adaoli** [comment]
Thanks. here is my project example https://github.com/adaoli/TestNav .  you will find fun handleLeftPan() not work for DetailTableViewController.swift.

**Comment by lkzhao** [comment]
Hey @adaoli,

Sorry about the late reply. Have been busy lately. 
The problem with your code is that the transition object is not initialized.
In my demo code. I passed the transition from the root ViewController down to the next ViewController.
I did that mainly because I only want a single transition so that the configuration are kept.

You can, however, initialize a new one.
So instead of writing:

``` swift
    var transition:ElasticTransition!
```

Do:

``` swift
    var transition = ElasticTransition()
```

**Comment by brettharvee** [comment]
Okay! I will definitely go in and change it. Thank you SO much. I am really excited to start implementing your elastic transition into my projects!

Brett Harvey

On Feb 7, 2016, at 6:54 PM, Luke Zhao <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey @adaolihttps://github.com/adaoli,

Sorry about the late reply. Have been busy lately.
The problem with your code is that the transition object is not initialized.
In my demo code. I passed the transition from the root ViewController down to the next ViewController.
I did that meanly because I only want a single transition so that the configuration are kept.

You can, however, initialize a new one.
So instead of writing:

```
var transition:ElasticTransition!
```

Do:

```
var transition = ElasticTransition()
```

**Comment by adaoli** [comment]
Thanks a million!
